// Action Type Constants
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const TOKEN_VALIDATION_SUCCESS = 'TOKEN_VALIDATION_SUCCESS';
export const TOKEN_VALIDATION_FAILED = 'TOKEN_VALIDATION_FAILED';

// RETURN CODES
export const IS_LOGGED_IN = "LOGGED_IN";