export const ONGOING_CONTESTS_SUCCESS = 'ONGOING_CONTESTS_SUCCESS';
export const ONGOING_CONTESTS_FAILED = 'ONGOING_CONTESTS_FAILED';

export const RECENT_SUBMISSIONS_SUCCESS = 'RECENT_SUBMISSIONS_SUCCESS';
export const RECENT_SUBMISSIONS_FAILED = 'RECENT_SUBMISSIONS_FAILED';

export const ONGOING_CONTESTS_THROBBER_TOGGLE = 'ONGOING_CONTESTS_THROBBER_TOGGLE';
export const RECENT_SUBMISSION_THROBBER_TOGGLE = 'RECENT_SUBMISSION_THROBBER_TOGGLE';
